name: Test & Build Next.js App

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main, beta, production, next]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21' # Use the node version that matches your development environment

      - name: Install dependencies
        run: pnpm install # Replace with pnpm install if using pnpm

      - name: Run Lint
        run: pnpm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21' # Use the node version that matches your development environment

      - name: Install dependencies
        run: pnpm install # Replace with pnpm install if using pnpm

      - name: Build the project
        run: pnpm run build
